# permissions for end users to view matgipredisservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matgipredisserver-viewer-role
rules:
- apiGroups:
  - matgip.matgip.real-estate.corp
  resources:
  - matgipredisservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matgip.matgip.real-estate.corp
  resources:
  - matgipredisservers/status
  verbs:
  - get
